global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "callmaker-api"
    static_configs:
      - targets: ["callmaker-backend:5000"]   # sesuaikan nama service backend kamu
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
